### PR TITLE
implemented SuspiciousAuthorFormatException

### LINKED ISSUE #103: Preventing Author Creation if "," in name
We want to enforce "natural sort order" for our author names (meaning *not* last, first)

We'll want to:
1) create a news type of Exception called e.g. `SuspiciousAuthorFormatException` for author names containing `,` in them
2) Update the Author class (and possible the add_book method) to check author name before creating a new book on openlibrary.org
3) add a test to `openlibrary-client` to verify that a `SuspiciousAuthorFormatException` is raised when a user attempts to create an author w/ a `,` in the name

### PR DESCRIPTION
**Pull request by deadPix3l**
This PR closes #103

## Description:
I highly recommend using a more defined exception (ValueError is most appropriate here) but i have done it as requested in #103. hope its good!

### CODE REVIEW

**Comment by mekarpeles** [comment]
lgtm -- @hornc would you like to check and merge?

**Comment by tfmorris** [comment]
I agree that it should  extend something more specific like value error

**Comment by hornc** [comment]
Thanks @deadPix3l , I would be happy with the `ValueError` change too, feel free to update and I'll review + merge.

**Comment by mekarpeles** [comment]
Did I misunderstand -- Was the suggestion for SuspiciousAuthorFormatException to extend ValueError? @tfmorris + @hornc? I do think it's useful to be able to single out which/what type of ValueError you want to catch, based on the situation. I also think **extending** `ValueError` is much more targeted than generically extending `Exception`

**Comment by deadPix3l** [comment]
@mekarpeles no problem. Inheriting suspiciousAuthorError from ValueError is another way to go. Although my suggestion was intended to actually use value error as I have changed.

It's your choice really. But there are differences to keep in mind. The main one is difficulty writing a billion except blocks for every custom error. It's easier to write a single except block for the more generic and noncustom exception.

Another is library support. Generally it's a good idea to not invent new exceptions if existing ones reflect your problem. You have an issue with the value of the author. So ValueError. 

A good rule of thumb is don't invent exceptions unless you intend to use them multiple times, for multiple things. That's what error messages and attributes are for.

In any case, it's purely your decision, and the changes are minor enough that I need not be involved anymore. Just wanted to give an opinion.

**Comment by mekarpeles** [comment]
Going to accept/merge and allow followups if anyone feels strongly about the more specific class case, a la `SuspiciousAuthorFormatException`

**Comment by tfmorris** [comment]
half a year late, but yes, the suggestion was to change
```
class SuspiciousAuthorFormatException(Exception):	
    pass
```
to 
```
class SuspiciousAuthorFormatException(ValueError):	
    pass
```
but plain old ```ValueError``` is fine too.

**Pull request merged**
